functions:
  my-function-01:
    publish-correct-body-through-api:
      request:
        type: api-gateway
        path: '/myapi'
        headers:
          Authorization: <base64 encoded>
      response:
        body:
          statusCode: 200
    publish-malformed-body-through-api:
      request:
        type: api-gateway
        path: '/myapi'
        headers:
          Authorization: <base64 encoded>
      response:
        body:
          statusCode: 200
    publish-correct-body-direct:
      request:
        type: manual
      response:
        body:
          statusCode: 200
    publish-malformed-body-direct:
      request:
        type: manual
      response:
        body:
          statusCode: 200

  my-function-02:
    unpublish-correct-body-through-api:
      request:
        type: api-gateway
        path: '/myapi'
        headers:
          Authorization: <base64 encoded>
      response:
        body:
          statusCode: 200
    unpublish-malformed-body-through-api:
      request:
        type: api-gateway
        path: '/myapi'
        headers:
          Authorization: <base64 encoded>
      response:
        body:
          statusCode: 200
    unpublish-correct-body-direct:
      request:
        type: manual
      response:
        body:
          statusCode: 200
    unpublish-malformed-body-direct:
      request:
        type: manual
      response:
        body:
          statusCode: 200
